_wandb:
    value:
        cli_version: 0.25.0
        e:
            fpygcsny6kwfu79o6d5la6od4rl50ofw:
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "42949664768"
                        used: "25758720000"
                email: bcorwin@uoregon.edu
                executable: /projects/bgmp/shared/Bi625/ML_Assignment/Conda_Envs/HumpbackClassifierEnv/bin/python
                git:
                    commit: d222c168e5b5f8a1571b1423bec8705c38f5a303
                    remote: https://github.com/Brandy-Corwin/HappyWhaleClassifier.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-7430a58e-7f19-1c29-cf5d-f507ff1ef3d0
                host: n0149.talapas.uoregon.edu
                memory:
                    total: "540092194816"
                os: Linux-4.18.0-553.69.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: <python with no main file>
                python: CPython 3.13.1
                root: /gpfs/home/bcorwin/HappyWhaleClassifier
                slurm:
                    cluster_name: talapas
                    conf: /var/spool/slurm/conf-cache/slurm.conf
                    cpus_on_node: "6"
                    cpus_per_task: "6"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: bgmp
                    job_cpus_per_node: "6"
                    job_end_time: "1772178352"
                    job_gid: "131"
                    job_gpus: "26"
                    job_id: "42374675"
                    job_name: sys/dashboard/sys/jupyter
                    job_nodelist: n0149
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1772149552"
                    job_uid: "287341"
                    job_user: bcorwin
                    jobid: "42374675"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: n0149
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /var/www/ood/apps/sys/dashboard
                    submit_host: ood1.talapas.uoregon.edu
                    task_pid: "1273326"
                    tasks_per_node: "1"
                    topology_addr: ibcore[1-6].ib13.n0149
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=6
                startedAt: "2026-02-26T23:56:50.605525Z"
                writerId: fpygcsny6kwfu79o6d5la6od4rl50ofw
        m: []
        python_version: 3.13.1
        session_history: code/_session_history.ipynb
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.1
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: Species
epochs:
    value: 5
learning rate:
    value: 0.001
